# Generated by Django 4.0.4 on 2022-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_soldier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
