# Generated by Django 4.0.4 on 2022-05-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_soldier_unit_alter_soldier_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(choices=[('Cardet', 'Cadet'), ('Corporal', 'Corporal'), ('Sergeant', 'Sergeant'), ('Lieutenant', 'Lieutenant'), ('Captain', 'Captain'), ('Major', 'Major'), ('Colonel', 'Colonel'), ('General', 'General'), ('Field Marshal', 'Field Marshal')], max_length=50),
        ),
    ]
