# Generated by Django 4.0.4 on 2022-05-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeaponBrand',
            new_name='WeaponCategory',
        ),
        migrations.AddField(
            model_name='weaponbrandsupplier',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.weaponcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weaponbrandsupplier',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
