# Generated by Django 4.0.4 on 2022-05-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_weaponbrand_weaponcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
