# Generated by Django 4.0.4 on 2022-05-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_weaponcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='weaponcategory',
            name='fa_object',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weaponcategory',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
