# Generated by Django 4.0.4 on 2022-05-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_weapon_id_weapon_weapon_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponassigned',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weaponassigned',
            name='was_destroyed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='weaponassigned',
            name='was_returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
