# Generated by Django 4.0.4 on 2022-05-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_weaponassigned_date_returned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weaponassigned',
            options={'verbose_name_plural': 'weapons assigned'},
        ),
        migrations.AlterModelOptions(
            name='weaponcategory',
            options={'verbose_name_plural': 'Weapon Categories'},
        ),
        migrations.AddField(
            model_name='weaponassigned',
            name='weapon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
